name: world_cup_2026
version: "1.0.0"
config-version: 2

profile: world_cup_2026

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  world_cup_2026:
    silver:
      +materialized: table
    gold:
      +materialized: table

seeds:
  world_cup_2026:
    bronze_squads:
      +column_types:
        age: varchar
        mp: integer
        starts: integer
        min: integer
        "90s": float
        gls: float
        ast: float
        pk: integer
        pkatt: integer
        crdy: integer
        crdr: integer
        xg: float
        xag: float
    bronze_market_value:
      +column_types:
        age: integer
        market_value_eur_m: float
